---

- name: NETW-3200 Determine if protocol is really needed
  ansible.builtin.lineinfile:
    dest: "{{ security_network_blacklist_modules_file }}"
    line: "install {{ item }} /bin/true"
    state: present
    create: yes
  with_items:
    - "{{ security_network_blacklist_modules }}"
  register: security_network_blacklist


- name: Attempt to remove the protocol module
  ansible.builtin.shell:
    cmd: "modprobe -r {{ item }}"
  ignore_errors: true
  when: security_network_blacklist.changed
  with_items:
    - "{{ security_network_blacklist_modules }}"
  # notify:
  #   - reboot