---

- name: PKGS-7346 Get packages to purge
  shell:
    cmd: "dpkg --list | grep ^rc | awk '{ print $2; }'"
  changed_when: false
  register: packages_not_purged


- name: PKGS-7346 Purge old/removed packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_lines:
    - "{{ packages_not_purged.stdout }}"
  become: true


- name: PKGS-7370, PKGS-7394, ACCT-9622 deb packages
  ansible.builtin.apt:
    name:
      - "{{ item }}"
    state: present
  become: true
  with_items:
    - "{{ security_apt_packges }}"


- name: ACCT-9622 acct
  ansible.builtin.apt:
    name:
      - "acct"
    state: present
  become: true


- name: ACCT-9626 sysstat
  ansible.builtin.apt:
    name:
      - "sysstat"
    state: present
  become: true


- name: ACCT-9632 auditd
  ansible.builtin.apt:
    name:
      - auditd
    state: present
  become: true


- name: FINT-4350 aide
  ansible.builtin.apt:
    name:
      - aide
    state: present
  become: true
  register: aide_init


- name: FINT-4350 aide - init 
  shell:
    cmd: "aideinit"
  when: aide_init.changed

# - name: 
# , , , HRDN-7230 chkrootkit, HRDN-7230 malware scanner, CRYP-8005 psuedo random, USB-3000 usbguard
# , , , chkrootkit, clamav, clamav-daemon, haveged, usbguard
#     state: present    
