---

- name: Lynis expects /etc/sudoers.d to be unreadable by “others”
  ansible.builtin.file:
    path: "/etc/sudoers.d"
    state: directory
    owner: root
    group: root
    mode: 0750
  become: true
